[project]
name = "lcls-parse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["numpy", "h5py", "scipy", "tables", "ipykernel"]
